Add optional non-global timeout parameter to functions that use timeouts
egineering-llc/RZBluetooth pull request #4
Opened 2019-02-28 15:47 UTC by mattremmel

2019-02-28 16:09 UTC, ghost requested changes
The code looks good to me but it would be nice to see a test or two demonstrating that it works.

2019-02-28 18:34 UTC, joshbrown-eg requested changes
The rest of this looks good. Agreed with Matt that tests would be nice.

2019-02-28 18:34 UTC, joshbrown-eg commented on RZBluetooth/Command/RZBCommandDispatch.h
> +- (void)dispatchCommand:(RZBCommand *)command timeout:(NSTimeInterval) timeout;
Spacing is inconsistent with the rest of the parameters in this file.

```suggestion
- (void)dispatchCommand:(RZBCommand *)command timeout:(NSTimeInterval)timeout;
```

2019-02-28 18:34 UTC, joshbrown-eg commented on RZBluetooth/Command/RZBCommandDispatch.m
> +- (void)dispatchCommand:(RZBCommand *)command timeout:(NSTimeInterval) timeout
Spacing.

```suggestion
- (void)dispatchCommand:(RZBCommand *)command timeout:(NSTimeInterval)timeout
```

2019-03-05 17:06 UTC, joshuatbrown requested changes

2019-03-05 17:06 UTC, joshuatbrown commented on RZBluetooth/Command/RZBCommandDispatch.m
> +- (void)dispatchCommand:(RZBCommand *)command timeout:(NSTimeInterval) timeout
```suggestion
- (void)dispatchCommand:(RZBCommand *)command timeout:(NSTimeInterval)timeout
```

Spacing is still off here. Proposing the fix.

2019-03-05 17:06 UTC, joshuatbrown commented on RZBluetoothTests/RZBCommandDispatchTests.m
> +}
Tests look good. I'll run them to verify that they pass for me.

2019-03-05 18:57 UTC, joshuatbrown commented
OK, so it turns out I'd have to add another remote in order to check out your branch and run the tests, so I'm going to just trust that you've already run them and they pass. Next time it'd be great if you can create a branch in the `egineering-llc` repo.

2019-03-05 18:57 UTC, joshuatbrown approved these changes

2019-03-05 19:22 UTC, mattremmel commented
@joshuatbrown I'm happy to do it in `egineering-llc` next time. I'm not sure i've got permissions to do that though. Or at least didn't when I started this.

2019-03-05 19:49 UTC, joshbrown-eg commented
@mattremmel Yeah, you didn't used to have write access but I granted it sometime in the last hour, so I think you should be able to next time.

2019-03-07 15:17 UTC, ghost approved these changes

2019-03-07 16:09 UTC, joshbrown-eg approved these changes

2019-03-08 14:00 UTC, merged